import { createFileRoute } from "@tanstack/react-router";
import { useMemo,useState } from "react";
import { ArrowLeftRight,ChevronLeft,ChevronRight,Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { PageIntro,DemoBadge,EmptyState } from "@/components/shared/common";
import { Reveal } from "@/components/shared/motion";
import { TransactionList } from "@/components/transactions/transaction-list";
import { mockTransactions } from "@/data/mockTransactions";
export const Route=createFileRoute("/transactions")({head:()=>({meta:[{title:"Transactions — Stellix"},{name:"description",content:"Search and review your Stellar wallet transaction activity."},{property:"og:title",content:"Transactions — Stellix"},{property:"og:description",content:"Search and review your Stellar wallet transaction activity."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:TransactionsPage});
function TransactionsPage(){const [search,setSearch]=useState("");const [asset,setAsset]=useState("all");const [type,setType]=useState("all");const [status,setStatus]=useState("all");const [date,setDate]=useState("all");const [page,setPage]=useState(1);const filtered=useMemo(()=>mockTransactions.filter(tx=>(!search||`${tx.counterparty} ${tx.memo} ${tx.hash}`.toLowerCase().includes(search.toLowerCase()))&&(asset==="all"||tx.asset===asset)&&(type==="all"||tx.type===type)&&(status==="all"||tx.status===status)&&(date==="all"||Date.now()-new Date(tx.timestamp).getTime()<Number(date)*86400000)),[search,asset,type,status,date]);const per=5;const pages=Math.max(1,Math.ceil(filtered.length/per));const rows=filtered.slice((page-1)*per,page*per);return <div className="space-y-7"><Reveal><PageIntro title="Transactions" description="Search, filter, and inspect your Stellar activity." action={<DemoBadge/>}/></Reveal><Reveal delay={50}><section className="panel"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><div className="relative md:col-span-2 xl:col-span-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search activity" className="pl-9"/></div>{[[asset,setAsset,"Asset",["USDC","XLM","EURC"]],[type,setType,"Type",["incoming","outgoing","payment","swap"]],[status,setStatus,"Status",["confirmed","pending","failed"]],[date,setDate,"Date",[["7","Last 7 days"],["30","Last 30 days"],["90","Last 90 days"]]]].map(([value,setValue,label,items])=><Select key={label as string} value={value as string} onValueChange={v=>{(setValue as (v:string)=>void)(v);setPage(1)}}><SelectTrigger><SelectValue placeholder={label as string}/></SelectTrigger><SelectContent><SelectItem value="all">All {String(label).toLowerCase()}</SelectItem>{(items as (string|string[])[]).map(item=>{const val=Array.isArray(item)?item[0]:item;const text=Array.isArray(item)?item[1]:item;return <SelectItem key={val} value={val}>{text}</SelectItem>})}</SelectContent></Select>)}</div></section></Reveal><Reveal>{rows.length?<TransactionList transactions={rows}/>:<EmptyState icon={ArrowLeftRight} title="No transactions found" description="Adjust your filters or search to see more activity."/>}</Reveal><div className="flex items-center justify-between text-sm text-muted-foreground"><span>{filtered.length} results</span><div className="flex items-center gap-2"><Button size="icon" variant="outline" aria-label="Previous page" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><span>Page {page} of {pages}</span><Button size="icon" variant="outline" aria-label="Next page" disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button></div></div></div>}
