import { ArrowDownLeft,ArrowLeftRight,ArrowUpRight,CreditCard,ExternalLink } from "lucide-react";
import type { Transaction } from "@/types";
import { TransactionStatusBadge } from "@/components/shared/status";
import { currency } from "@/components/shared/common";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useState } from "react";
const icons={incoming:ArrowDownLeft,outgoing:ArrowUpRight,payment:CreditCard,swap:ArrowLeftRight};
export function TransactionList({transactions,limit,onViewAll}:{transactions:Transaction[];limit?:number;onViewAll?:()=>void}){const [selected,setSelected]=useState<Transaction>();const rows=limit?transactions.slice(0,limit):transactions;return <><div className="hidden overflow-hidden border border-border md:block"><table className="w-full text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Transaction</th><th className="px-4 py-3 font-medium">Asset</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Amount</th></tr></thead><tbody className="divide-y divide-border">{rows.map(tx=>{const Icon=icons[tx.type];return <tr key={tx.id} className="cursor-pointer transition-colors hover:bg-muted/40" onClick={()=>setSelected(tx)}><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-secondary text-primary"><Icon className="size-4"/></span><div><p className="font-medium capitalize">{tx.type}</p><p className="text-xs text-muted-foreground">{tx.counterparty} · {new Date(tx.timestamp).toLocaleDateString()}</p></div></div></td><td className="px-4 py-3">{tx.asset}</td><td className="px-4 py-3"><TransactionStatusBadge status={tx.status}/></td><td className="px-4 py-3 text-right font-mono font-medium">{tx.type==="incoming"?"+":"−"}{currency(tx.usdValue)}</td></tr>})}</tbody></table></div><div className="space-y-2 md:hidden">{rows.map(tx=>{const Icon=icons[tx.type];return <button key={tx.id} onClick={()=>setSelected(tx)} className="flex w-full items-center gap-3 border border-border bg-card p-4 text-left"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-secondary text-primary"><Icon className="size-5"/></span><span className="min-w-0 flex-1"><span className="block truncate font-medium">{tx.counterparty}</span><span className="text-xs text-muted-foreground">{tx.asset} · {new Date(tx.timestamp).toLocaleDateString()}</span></span><span className="text-right"><span className="block font-mono text-sm font-semibold">{tx.type==="incoming"?"+":"−"}{currency(tx.usdValue)}</span><TransactionStatusBadge status={tx.status}/></span></button>})}</div>{onViewAll&&<Button variant="ghost" className="mt-3 w-full" onClick={onViewAll}>View all transactions</Button>}<TransactionDialog transaction={selected} onClose={()=>setSelected(undefined)}/></>}
export function TransactionDialog({transaction,onClose}:{transaction:Transaction|undefined;onClose:()=>void}){return <Dialog open={!!transaction} onOpenChange={open=>!open&&onClose()}><DialogContent><DialogHeader><DialogTitle>Transaction details</DialogTitle><DialogDescription>Demo Stellar network activity</DialogDescription></DialogHeader>{transaction&&<div className="detail-list">{[["Hash",transaction.hash],["Type",transaction.type],["Amount",`${transaction.amount.toLocaleString()} ${transaction.asset}`],["From",transaction.from],["To",transaction.to],["Status",transaction.status],["Timestamp",new Date(transaction.timestamp).toLocaleString()],["Memo",transaction.memo??"—"],["Network fee",`${transaction.fee} XLM`]].map(([k,v])=><div key={k}><span>{k}</span><strong className="max-w-[65%] break-all text-right">{v}</strong></div>)}<Button asChild className="mt-2 w-full"><a href={transaction.explorerUrl} target="_blank" rel="noreferrer"><ExternalLink/>View on Stellar Explorer</a></Button></div>}</DialogContent></Dialog>}
